apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servivex
  namespace: sthapa
spec:
  interval: 5m
  releaseName: servicex
  chart:
    spec:
      chart: servicex
      sourceRef:
        kind: HelmRepository
        name: servicex
  valuesFrom:
    - kind: ConfigMap
      name: values

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: servicex
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: develop
  url: https://github.com/sthapa/ServiceX/

