---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: servicex
  namespace: sthapa
spec:
  interval: 5m0s
  url: https://github.com/sthapa/servicex
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: servicex
  validation: client

